[package]
name = "question_3"
version = "0.1.0"
authors = ["mudassir"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
func_call = {path = "func_call"}
